services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    network_mode: host
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PASSWORD}
      FTLCONF_REPLY_ADDR4: ${IP}
      ADMIN_EMAIL: ${EMAIL}
      PIHOLE_DNS_: ${DNS1};1.1.1.1;1.0.0.1;8.8.8.8;8.8.4.4
      DNSSEC: "false"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
      REV_SERVER: "true"
      REV_SERVER_DOMAIN: ${LOCAL}
      REV_SERVER_TARGET: ${GW}
      REV_SERVER_CIDR: ${LAN}
      DHCP_ACTIVE: "false"
      TEMPERATUREUNIT: f
      WEBTHEME: "default-dark"       
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped

