services:

  app:
    networks:
      - backend
      - web-proxy
    dns:
      - 192.168.9.9
      - 192.168.9.254
    restart: unless-stopped
    image: bbilly1/tubearchivist
    volumes:
      - /mnt/Media/Videos/Web/youtube:/youtube
      - ./cache:/cache
    environment:
      - ES_URL=http://es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=tube.neverhood.space         # set your host name
      - TA_USERNAME=tube           # your initial TA credentials
      - TA_PASSWORD=verysecret              # your initial TA credentials
      - ELASTIC_PASSWORD=$ES_PASSWORD         # set password for Elasticsearch
      - TZ:$TZ                 # set your time zone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - es
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.tube.entrypoints=websecure
      - traefik.http.routers.tube.tls.certresolver=letsencrypt-do
      - traefik.http.routers.tube.rule=Host(`tube.${DOMAINNAME}`)
      - traefik.http.routers.tube.service=tube-svc
      - traefik.http.services.tube-svc.loadbalancer.server.port=8000

  redis:
    image: redis/redis-stack-server
    networks:
      - backend
    expose:
      - "6379"
    restart: unless-stopped
    volumes:
      - ./redis:/data
    depends_on:
      - es
    environment:
      - TZ:$TZ

  es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.13.2
    networks:
      - backend
    expose:
      - "9200"
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=$ES_PASSWORD       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
      - TZ:$TZ
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme

networks:
  backend:
  web-proxy:
    external: true

