services:

  app:
    networks:
      - backend
      - webproxy
    restart: unless-stopped
    image: bbilly1/tubearchivist
    volumes:
      - ${MEDIA_DIR}/Videos/Web/youtube:/youtube
      - ./cache:/cache
    environment:
      - ES_URL=http://es:9200
      - REDIS_HOST=redis
      - HOST_UID=${PUID}
      - HOST_GID=${PGID}
      - TA_HOST=tube.${DOMAINNAME}
      - TA_USERNAME=${TA_USER}
      - TA_PASSWORD=${TA_PASSWORD}
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - ENABLE_CAST=true
      - TZ:${TZ}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - es
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.tube.entrypoints=websecure
      - traefik.http.routers.tube.tls.certresolver=letsencrypt-do
      - traefik.http.routers.tube.rule=Host(`tube.${DOMAINNAME}`)
      - traefik.http.routers.tube.service=tube-svc
      - traefik.http.services.tube-svc.loadbalancer.server.port=8000

  redis:
    image: redis/redis-stack-server
    networks:
      - backend
    expose:
      - "6379"
    restart: unless-stopped
    volumes:
      - ./redis:/data
    depends_on:
      - es
    environment:
      - TZ:${TZ}

  es:
    image: bbilly1/tubearchivist-es
    networks:
      - backend
    expose:
      - "9200"
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
      - TZ:$TZ
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es:/usr/share/elasticsearch/data

networks:
  backend:
  webproxy:
    external: true

