services:

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    networks:
      - wings0
      - webproxy
    ports:
      - "2022:2022"
    tty: true
    environment:
      TZ: ${TZ}
      WINGS_UID: ${PUID}
      WINGS_GID: ${PGID}
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "./etc/:/etc/pterodactyl/"
      - "./lib/:/srv/pterodactyl/lib/"
      - "./log/:/var/log/pterodactyl/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"
    labels:
     - traefik.enable=true
     - traefik.http.routers.pterodactyl.rule=Host(`ptero-node0.${DOMAINNAME}`)
     - traefik.http.routers.pterodactyl.entrypoints=websecure
     - traefik.http.routers.pterodactyl.tls=true
     - traefik.http.routers.pterodactyl.tls.certresolver=letsencrypt-do
     - traefik.http.routers.pterodactyl.service=pterodactyl-svc
     - traefik.http.services.pterodactyl-svc.loadbalancer.server.port=443
    restart: unless-stopped


networks:

  wings0:
    name: wings0
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.21.0/24
          gateway: 10.9.21.1
    driver_opts:
      com.docker.network.bridge.name: wings0

  webproxy:
    external: true
