services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./hass:/config
      - ${TZ_VOL}
    restart: unless-stopped
    privileged: true
    network_mode: host

